// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['main']['App']['AddGame'](arg1);
}

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DeleteWorkOrder(arg1) {
  return window['go']['main']['App']['DeleteWorkOrder'](arg1);
}

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function GetDeviceList() {
  return window['go']['main']['App']['GetDeviceList']();
}

export function GetGameList(arg1) {
  return window['go']['main']['App']['GetGameList'](arg1);
}

export function GetOrderGameList(arg1) {
  return window['go']['main']['App']['GetOrderGameList'](arg1);
}

export function GetWorkOrder(arg1) {
  return window['go']['main']['App']['GetWorkOrder'](arg1);
}

export function UpdateAnnouncement(arg1) {
  return window['go']['main']['App']['UpdateAnnouncement'](arg1);
}

export function UpdateGame(arg1) {
  return window['go']['main']['App']['UpdateGame'](arg1);
}
